### PR TITLE
Filter pods which are not replicatset or statefulset

### LINKED ISSUE #267: --service arg: Failed to resolve the ReplicaSet backing the service
**Describe the bug**
Continuation from https://github.com/Azure/Bridge-To-Kubernetes/issues/246

Looks like bridge-to-kubernetes can connect now, but it cannot find the pod(?)

**Mention the platform you are using**
aarch64-darwin (13.3.1 (22E261))

**To Reproduce**
```
❯ KUBECTL_PROXY=http://127.0.0.1:8001 BRIDGE_ENVIRONMENT=dev ./dsc connect --service data-center-api --local-port 3001 --namespace compliance-staging --use-kubernetes-service-environment-variables
Connect operation failed.
Stopping workload and cleaning up...
An unexpected error occurred: 'Failed to resolve the ReplicaSet backing the service 'data-center-api'.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/var/folders/xs/qydcvbpd3nnd5fyt_295n_fw0000gq/T/Bridge To Kubernetes'.
❯ cat /var/folders/xs/qydcvbpd3nnd5fyt_295n_fw0000gq/T/Bridge\ To\ Kubernetes/*
2023-05-05T02:07:14.7712710Z | Library | TRACE | Pulling kubeconfig...\nOperation context: <json>{"clientRequestId":null,"correlationId":":aa6a604e1680:cf5b1ebc04af","requestId":null,"userSubscriptionId":null,"startTime":"2023-05-05T02:07:14.685188\u002B00:00","userAgent":"MindaroCli/1.0.20230502.1","requestHttpMethod":null,"requestUri":null,"version":"1.0.20230502.1","requestHeaders":{},"loggingProperties":{"ApplicationName":"Library","DeviceOperatingSystem":"Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000","Framework":".NET 6.0.14","MacAddressHash":"4a01e708fd7631358dfc5ca1a15a2c9fecbd11eea3d7386a4c9e468fd0617c7d","ProcessId":79315,"TargetEnvironment":"Development"}}</json>
2023-05-05T02:07:15.0110000Z | Library | TRACE | Event: CloudProvider <json>{"properties":{"ClusterFQDNDomain":"eqs.tools"},"metrics":null}</json>
2023-05-05T02:07:15.5728820Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"ListPodsInNamespaceAsync","success":true,"duration":null,"properties":{}}</json>
2023-05-05T02:07:15.5883430Z | Library | TRACE | Event: KubernetesManagementClient-CheckCredentialsAsync <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":524}}</json>\nOperation context: <json>{"clientRequestId":"709ddae9-0397-4a12-b11f-6e9043446192","correlationId":":aa6a604e1680:6aef88abe504","requestId":null,"userSubscriptionId":null,"startTime":"2023-05-05T02:07:14.685188\u002B00:00","userAgent":"MindaroCli/1.0.20230502.1","requestHttpMethod":null,"requestUri":null,"version":"1.0.20230502.1","requestHeaders":{},"loggingProperties":{"ApplicationName":"Library","DeviceOperatingSystem":"Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000","Framework":".NET 6.0.14","MacAddressHash":"4a01e708fd7631358dfc5ca1a15a2c9fecbd11eea3d7386a4c9e468fd0617c7d","ProcessId":79315,"TargetEnvironment":"Development"}}</json>
2023-05-05T02:07:15.8032620Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"ListPodsInNamespaceAsync","success":true,"duration":null,"properties":{}}</json>
2023-05-05T02:07:15.8988690Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"GetV1ServiceAsync","success":true,"duration":null,"properties":{}}</json>
2023-05-05T02:07:16.0187330Z | Library | TRACE | Dependency: Kubernetes <json>{"target":"ListPodsInNamespaceAsync","success":true,"duration":null,"properties":{}}</json>
2023-05-05T02:07:16.0294320Z | Library | TRACE | Event: KubernetesRemoteEnvironmentManager-GetPodsFromService <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":127}}</json>\nOperation context: <json>{"clientRequestId":null,"correlationId":":aa6a604e1680:54d09e98ed9a","requestId":null,"userSubscriptionId":null,"startTime":"2023-05-05T02:07:14.685188\u002B00:00","userAgent":"MindaroCli/1.0.20230502.1","requestHttpMethod":null,"requestUri":null,"version":"1.0.20230502.1","requestHeaders":{},"loggingProperties":{"ApplicationName":"Library","DeviceOperatingSystem":"Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000","Framework":".NET 6.0.14","MacAddressHash":"4a01e708fd7631358dfc5ca1a15a2c9fecbd11eea3d7386a4c9e468fd0617c7d","ProcessId":79315,"TargetEnvironment":"Development","IsRoutingEnabled":false}}</json>
2023-05-05T02:07:16.0300630Z | Library | TRACE | Resolved 4 from service.
2023-05-05T02:07:16.0310010Z | Library | TRACE | Max number of containers in pod: 1, min number of containers in pod: 1
2023-05-05T02:07:16.0409230Z | Library | TRACE | Event: ConnectManagementClient-StartRemoteAgent <json>{"properties":{"Result":"Failed"},"metrics":{"DurationInMs":403}}</json>
2023-05-05T02:07:16.0421500Z | Library | ERROR | Failed to start remote agent.
2023-05-05T02:07:16.0894030Z | Library | ERROR | Logging handled exception: System.InvalidOperationException: {"Message":"Failed to resolve the ReplicaSet backing the service \u0027data-center-api\u0027.","Data":{},"InnerException":null,"HelpLink":null,"Source":"Microsoft.BridgeToKubernetes.Library","HResult":-2146233079,"StackTrace":"   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.GetOwningSetFromPods(IEnumerable\u00601 pods, String serviceName)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveBackingObjectDetailsAsync(RemoteContainerConnectionDetails remoteContainerConnectionDetails, IEnumerable\u00601 pods, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveConnectionDetails(RemoteContainerConnectionDetails remoteContainerConnectionDetails, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.\u003C\u003Ec__DisplayClass17_0.\u003C\u003C-ctor\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.\u003C\u003Ec__DisplayClass21_0.\u003C\u003CStartRemoteAgentAsync\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func\u00601 func, FailureConfig failureConfig)"}
2023-05-05T02:07:16.1088150Z | Library | TRACE | Event: KubernetesRemoteEnvironmentManager-Restore <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":1}}</json>
2023-05-05T02:07:16.1090610Z | Library | TRACE | Event: KubernetesRemoteEnvironmentManager-RestoreRemoteAgent <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":6}}</json>
2023-05-05T02:07:16.1091540Z | Library | TRACE | Event: ConnectManagementClient-RestoreOriginalRemoteContainer <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":7}}</json>
2023-05-05T02:07:16.1117490Z | Library | TRACE | Event: LocalEnvironmentManager-StopWorkload <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":0}}</json>
2023-05-05T02:07:16.1118630Z | Library | TRACE | Event: ConnectManagementClient-StopLocalConnection <json>{"properties":{"Result":"Succeeded"},"metrics":{"DurationInMs":1}}</json>
2023-05-05T02:07:14.5852890Z | MindaroCli | TRACE | Event: Command.Start <json>{"properties":{"Arguments":"connect --service data-center-api --local-port 3001 --namespace compliance-staging --use-kubernetes-service-environment-variables","IsRoutingEnabled":"false"},"metrics":null}</json>\nOperation context: <json>{"clientRequestId":null,"correlationId":":aa6a604e1680","requestId":null,"userSubscriptionId":null,"startTime":"2023-05-05T02:07:14.155692\u002B00:00","userAgent":"MindaroCli/1.0.20230502.1","requestHttpMethod":null,"requestUri":null,"version":"1.0.20230502.1","requestHeaders":{},"loggingProperties":{"ApplicationName":"MindaroCli","DeviceOperatingSystem":"Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000","Framework":".NET 6.0.14","MacAddressHash":"4a01e708fd7631358dfc5ca1a15a2c9fecbd11eea3d7386a4c9e468fd0617c7d","ProcessId":79315,"TargetEnvironment":"Development","CommandId":"aa6a604e1680"}}</json>
2023-05-05T02:07:14.7273280Z | MindaroCli | TRACE | Running Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand...\nOperation context: <json>{"clientRequestId":null,"correlationId":":aa6a604e1680","requestId":null,"userSubscriptionId":null,"startTime":"2023-05-05T02:07:14.155692\u002B00:00","userAgent":"MindaroCli/1.0.20230502.1","requestHttpMethod":null,"requestUri":null,"version":"1.0.20230502.1","requestHeaders":{},"loggingProperties":{"ApplicationName":"MindaroCli","DeviceOperatingSystem":"Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000","Framework":".NET 6.0.14","MacAddressHash":"4a01e708fd7631358dfc5ca1a15a2c9fecbd11eea3d7386a4c9e468fd0617c7d","ProcessId":79315,"TargetEnvironment":"Development","CommandId":"aa6a604e1680","TargetServiceName":"data-center-api","IsRoutingEnabled":false}}</json>
2023-05-05T02:07:16.0928270Z | MindaroCli | ERROR | Dependency: Service Run - Port Forward <json>{"target":null,"success":false,"duration":null,"properties":{"RequestId":"null","ClientRequestId":"null","CorrelationRequestId":"null"}}</json>
2023-05-05T02:07:16.0945560Z | MindaroCli | ERROR | ServiceConnectCommand.ExecuteInnerAsync caught exception System.InvalidOperationException: Failed to resolve the ReplicaSet backing the service 'data-center-api'.\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.GetOwningSetFromPods(IEnumerable`1 pods, String serviceName)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveBackingObjectDetailsAsync(RemoteContainerConnectionDetails remoteContainerConnectionDetails, IEnumerable`1 pods, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveConnectionDetails(RemoteContainerConnectionDetails remoteContainerConnectionDetails, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.<>c__DisplayClass17_0.<<-ctor>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.<>c__DisplayClass21_0.<<StartRemoteAgentAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig)\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.StartRemoteAgentAsync(CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action workloadStartedHandler, CancellationToken cancellationToken, IRoutingManagementClient routingManagementClient)
2023-05-05T02:07:16.0972560Z | MindaroCli | ERROR | Connect operation failed.\n
2023-05-05T02:07:16.0997960Z | MindaroCli | TRACE | Stopping workload and cleaning up...\n
2023-05-05T02:07:16.1128020Z | MindaroCli | ERROR | Dependency: Service Run - Port Forward <json>{"target":null,"success":false,"duration":null,"properties":{"RequestId":"null","ClientRequestId":"null","CorrelationRequestId":"null"}}</json>
2023-05-05T02:07:16.1186060Z | MindaroCli | ERROR | An unexpected error occurred: 'Failed to resolve the ReplicaSet backing the service 'data-center-api'.'\n
2023-05-05T02:07:16.1189610Z | MindaroCli | ERROR | To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.\n
2023-05-05T02:07:16.1195610Z | MindaroCli | ERROR | For diagnostic information, see logs at '/var/folders/xs/qydcvbpd3nnd5fyt_295n_fw0000gq/T/Bridge To Kubernetes'.\n
2023-05-05T02:07:16.1227800Z | MindaroCli | ERROR | Logging handled exception: System.InvalidOperationException: {"Message":"Failed to resolve the ReplicaSet backing the service \u0027data-center-api\u0027.","Data":{},"InnerException":null,"HelpLink":null,"Source":"Microsoft.BridgeToKubernetes.Library","HResult":-2146233079,"StackTrace":"   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.GetOwningSetFromPods(IEnumerable\u00601 pods, String serviceName)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveBackingObjectDetailsAsync(RemoteContainerConnectionDetails remoteContainerConnectionDetails, IEnumerable\u00601 pods, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.Utilities.RemoteContainerConnectionDetailsResolver.ResolveConnectionDetails(RemoteContainerConnectionDetails remoteContainerConnectionDetails, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.\u003C\u003Ec__DisplayClass17_0.\u003C\u003C-ctor\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.\u003C\u003Ec__DisplayClass21_0.\u003C\u003CStartRemoteAgentAsync\u003Eb__0\u003Ed.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ManagementClientExceptionStrategy.RunWithHandlingAsync[T](Func\u00601 func, FailureConfig failureConfig)\n   at Microsoft.BridgeToKubernetes.Library.ManagementClients.ConnectManagementClient.StartRemoteAgentAsync(CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action workloadStartedHandler, CancellationToken cancellationToken, IRoutingManagementClient routingManagementClient)\n   at Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand.ExecuteInnerAsync(IConnectManagementClient connectManagementClient, Action workloadStartedHandler, CancellationToken cancellationToken, IRoutingManagementClient routingManagementClient)\n   at Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand.ExecuteAsync()\n   at Microsoft.BridgeToKubernetes.Exe.CliApp.RunCommandAsync(String[] args, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Exe.CliApp.ExecuteAsync(String[] args, CancellationToken cancellationToken)"}
2023-05-05T02:07:16.1264340Z | MindaroCli | TRACE | Event: Command.End <json>{"properties":{"Arguments":"connect --service data-center-api --local-port 3001 --namespace compliance-staging --use-kubernetes-service-environment-variables","Result":"Failed","FailureReason2":"Failed to resolve the ReplicaSet backing the service \u0027data-center-api\u0027."},"metrics":{"Duration":1691}}</json>
```

**Additional context**
I was asked to provide output of this
```
❯ kubectl get pod -n compliance-staging -l 'name=data-center-api' -o json
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": ""
    }
}
```
Although not sure why is it searching by name= label, we don't have those. Instead we use app= labels
`kubectl get pod -n compliance-staging -l 'app=data-center-api' -o json`returns [better looking json](https://github.com/Azure/Bridge-To-Kubernetes/files/11407709/scratch_2.txt)

Note: With --pod this works correctly

### PR DESCRIPTION
**Pull request by hsubramanianaks**
This PR is to fix #267. 
Root cause was if a user cluster contains multiple pods with same/similar name but different kind like pod-a is replicaset and pod-a-job is job, code is failing to recognize this and throws errors.

### CODE REVIEW

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs [hunk 1]
```diff
@@ -328,27 +343,34 @@ internal class RemoteContainerConnectionDetailsResolver
                 {
                     throw new UserVisibleException(_operationContext, Resources.ResourceNotSupportedFormat, Product.Name);
                 }
+                _log.Info("OwningSets name:" + owningSets);
```
Comment (hsubramanianaks) [inline src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:346]: I will remove these temporary log statements which was added to triage once user confirms it is working. Thanks.

**Review by Vidya2606 — DISMISSED** [review]
LGTM

File: src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs [hunk 2]
```diff
@@ -38,7 +37,7 @@ public RemoteContainerConnectionDetailsResolverTests()
         public async void ResolveConnectionDetails_RestoreCheck(int numServices, bool hasRestore, string phase)
         {
             // Set up
-            ConfigurePods(numPods: numServices, namingFunction: (i) => hasRestore && i == 0 ? $"myapp-restore-{i}" : $"myapp-{i}", phaseFunction: (i) => i == 0 ? phase : "Running");
+            ConfigurePods(numPods: numServices, namingFunction: (i) => hasRestore && i == 0 ? $"myapp-restore-{i}" : $"myapp-{i}", phaseFunction: (i) => i == 0 ? phase : "Running", "Job", "linux");
```
Comment (Tatsinnit) [inline src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs:40]: 💡 Idea/thoughts please: we could have an enum of state and have these `running et. al.` as follows, will be consistent and possible just fyi to casing inconsistency as well 

```*.cs
enum phase 
{
  Running,
  Job,
  Linux
}
```

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs [hunk 3]
```diff
@@ -210,25 +210,29 @@ internal class RemoteContainerConnectionDetailsResolver
...
+            _log.Info($"Owning object type: {owningObjectType}");
             if (string.Equals(owningObjectType, "ReplicaSet"))
             {
+                _log.Info("Inside if condition for replicaset");
                 // There is a single common replicaSet owning all the pods. Time to make sure there is a deployment owning it
                 var replicaSet = await _kubernetesClient.GetV1ReplicaSetAsync(remoteContainerConnectionDetails.NamespaceName, owningSetName, cancellationToken: cancellationToken);
                 if (replicaSet == null || replicaSet.Metadata?.OwnerReferences == null)
                 {
                     // replicaSet not found or no deployment owning it
+                    _log.Info("replicaset is null:"+ replicaSet);
```
Comment (Tatsinnit) [inline src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:222]: 💡 nit: most of the other logging has capital initial letter - just fyi - in case this is anything you want to cater.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs [hunk 4]
```diff
@@ -293,6 +297,15 @@ internal class RemoteContainerConnectionDetailsResolver
                         _log.Warning("{0} pods found, but they are all running RemoteAgent", pods.Count);
                         throw new UserVisibleException(_operationContext, Resources.SpecifiedServiceBackedByMultipleRemoteAgents, service.Metadata?.Name, pods.Count);
                     }
+
+                    // filter pods which are not replicaset or statefulset
+                    podsNotRunningDevHostAgent = podsNotRunningDevHostAgent.Where(p => p.Metadata?.OwnerReferences?.Any(r => StringComparer.OrdinalIgnoreCase.Equals(r.Kind, "ReplicaSet") || StringComparer.OrdinalIgnoreCase.Equals(r.Kind, "StatefulSet")) ?? false);
```
Comment (Tatsinnit) [inline src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:302]: 💡 for `nullable types` do we care to inform user or this is fine?

Please note: Also how about we enum the string match here for anywhere else if we need to use. like `ReplicaSet` or `StatefulSet` et. al.?

**Review by Tatsinnit — APPROVED** [review]
❤️🙏☕️ Thank you of this, added few comments, I guess regarding actual behaviour I am sure we have tested this, and hopefully no existing behaviour will be impacted. Thank you.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs (hunk 3 above)
Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:222]: these are temporary logs once E2E and user confirms it is working I will remove them. Thank you.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs (hunk 4 above)
Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:302]: Yes of course I can create a Enum for ReplicaSet and StatefulSet. For nullable types ex: what if metadata or owner references is empty ? If they are empty I don't think it is operational or working pod and user would get more errors.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs [hunk 5]
```diff
@@ -210,25 +210,29 @@ internal class RemoteContainerConnectionDetailsResolver
             CancellationToken cancellationToken)
         {
             (var owningSetName, var owningObjectType) = GetOwningSetFromPods(pods, remoteContainerConnectionDetails.ServiceName);
-            _log.Verbose($"Owning object type: {owningObjectType}");
+            _log.Info($"Owning object type: {owningObjectType}");
```
[the remark this answers is not in the document]
Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:213]: Thanks I will change this back, it was missed.

File: src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs (hunk 2 above)
Comment (hsubramanianaks) [reply src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs:40]: Sure will add them as Enum for test class file.

Comment (peterbom) [reply src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs:40]: This threw me at first. "Job" and "linux" are actually different arguments to the `ConfigurePods` function, but at first glance they look like some kind of multi-return type from `phaseFunction`.

I think named arguments would help a lot here, even though they'd make the function call really long. To deal with that, you could just wrap the lines (one arg per line), or maybe create a struct/record type for the parameters (which you could maybe argue is overkill).

Comment (peterbom) [reply src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs:40]: I'm not totally sure if Enums will work here, because we might not have a constrained set of possible values for `kind` and `nodeSelector`.

Comment (hsubramanianaks) [reply src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs:40]: good point @peterbom. I was thinking to create Enum's for Phase - Running, Pending etc.. similarly for nodeSelector - linux, windows etc.. I think Tats would have meant the same.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs (hunk 4 above)
Comment (peterbom) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:302]: You can have a working pod that has no owner property if the pod is created directly, can't you?

Unrelated: I think it'd be nice to simplify the linq expression here by introducing an intermediate function. For example, you could change line 302 to:
```csharp
podsNotRunningDevHostAgent = podsNotRunningDevHostAgent.Where(p => p.IsOwnerOfKind("ReplicaSet", "StatefulSet"));
```
I think having a named function in there makes the intent clearer - what do you reckon? You could put the implementation in `V1podExtensions.cs`, like:
```csharp
        public static bool IsOwnerOfKind(this V1Pod pod, params string[] kinds) =>
            pod.Metadata?.OwnerReferences?.Any(r => kinds.Any(k => StringComparer.OrdinalIgnoreCase.Equals(r.Kind, k))) ?? false;
```

Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:302]: updated the code as per your suggestion, but will see how pods without owner references will affect this change.

**Review by peterbom — APPROVED** [review]
Looks good! Maybe some considerations for future work:
- Would it be possible to support Jobs, or would that never make sense?
- I wonder if we could abstract the logic for Replica Sets and Stateful Sets into classes that implement a common interface, to cut down the amount of conditional logic.

**Comment by hsubramanianaks** [comment]
> Looks good! Maybe some considerations for future work:
> 
> * Would it be possible to support Jobs, or would that never make sense?
> * I wonder if we could abstract the logic for Replica Sets and Stateful Sets into classes that implement a common interface, to cut down the amount of conditional logic.

@peterbom I am not sure if ever debugging jobs make sense, may be we can ask some of the users if it ever make sense to debug jobs because jobs are one time activity and moves to completed state. 

Yes of course we can do the refactor/restructure to reduce conditional statements, but it will be a future work.

**Review by peterbom — APPROVED** [review]

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs (hunk 3 above)
Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs]: Testing team confirmed it is working.

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs [hunk 6]
```diff
@@ -293,6 +293,15 @@ internal class RemoteContainerConnectionDetailsResolver
                         _log.Warning("{0} pods found, but they are all running RemoteAgent", pods.Count);
                         throw new UserVisibleException(_operationContext, Resources.SpecifiedServiceBackedByMultipleRemoteAgents, service.Metadata?.Name, pods.Count);
                     }
+
+                    // filter pods which are not replicaset or statefulset
+                    podsNotRunningDevHostAgent = podsNotRunningDevHostAgent.Where(p => p.IsOwnerOfKind("ReplicaSet", "StatefulSet"));
+                    if (podsNotRunningDevHostAgent.Count() == 0)
+                    {
+                        _log.Warning("{0} pods found, after filtering pods which are of kind replicaset or statefulset", pods.Count);
```
Comment (gambtho) [inline src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs:301]: maybe simplify the message -- {0} pods found of kind replicaset or statefulset

**Review by gambtho — APPROVED** [review]

File: src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs (hunk 6 above)
Comment (hsubramanianaks) [reply src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs]: updated the message. Thanks for the suggestion.

**Review by gambtho — APPROVED** [review]

**Review by peterbom — APPROVED** [review]
