### PR TITLE
Fix for failed to launch endpointmanager - retry with sudo

### LINKED ISSUE #318: Failed to Launch endpointmanager - /dev/tty No Such device or address
**Describe the bug**
Failed to Launch endpointmanager - /dev/tty No Such device or address

**Mention the platform you are using**
Linux/Ubuntu/Debian

**To Reproduce**
Debug using Bridge vscode extension 

**Expected behavior**
Should launch endpointmanager without issues

**Logs:**
```
2023-09-21T07:32:36.8491570Z | Library | TRACE | Launch EndpointManager: pkexec env HOME="/home/azuretester/" bash -c "\"/home/azuretester/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/EndpointManager/EndpointManager\" \"azuretester\" \"/home/azuretester/.bridge/EndpointManager/EndpointManagerSocket\" \"/tmp/Bridge To Kubernetes\" \"5c15b3ad-767d-4c89-9e86-7a5fdc25d6751695281330503:3b365db07195:b0d47f50aab9:101fd79a0377\" &> /dev/null &"
2023-09-21T07:32:36.8496842Z | Library | TRACE | Setting the 'DOTNET_ROOT' environment variable with '/home/azuretester/.config/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet' while launching 'EndpointManager'.
2023-09-21T07:32:36.8553423Z | Library | TRACE | Launch output: Waiting for process 12471
2023-09-21T07:32:36.8724716Z | Library | TRACE | Launch output: Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address
2023-09-21T07:32:36.8738272Z | Library | TRACE | Launch
 output: Process has exited with exit code 127
```
**Additional context**

### PR DESCRIPTION
**Pull request by hsubramanianaks**
This PR is to fix #318 , enhancing the code to retry with Sudo if it fails for any Linux distribution and little refactoring of code by replacing if/else with switch for readability.

Test Results:

Tested in Debian Linux VM to make sure it works, and it failed previously.  @cxznmhdcxz FYIP.
```
azuretester@azds-vm-debian:~/forked/Bridge-To-Kubernetes/src/dsc/bin/Debug/net7.0/linux-x64/publish$ ./dsc connect --service stats-api --namespace todoapp --local-port 3001 --control-port 4001
Waiting for 'stats-api-58485d9b5b-vwkh9' in namespace 'todoapp' to reach running state...
Deployment 'todoapp/stats-api' patched to run agent.
Remote agent deployed in container 'stats-api' in pod 'stats-api-58485d9b5b-vwkh9'.
Preparing to run Bridge To Kubernetes configured as pod todoapp/stats-api-58485d9b5b-vwkh9 ...
Connection established.
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ===
Authentication is needed to run `/usr/bin/env' as the super user
Authenticating as: Debian (azuretester)
Password: 
==== AUTHENTICATION FAILED ===
Waiting for EndpointManager to come up ...
EndpointManager came up successfully.
Hosts file updated.
Service 'stats-api' is available on 127.1.1.1:80.
Service 'stats-queue' is available on 127.1.1.2:5672.
Service 'todos-db' is available on 127.1.1.3:27017.
Service 'database-api' is available on 127.1.1.4:80.
Service 'stats-cache' is available on 127.1.1.5:6379.
Service 'frontend' is available on 127.1.1.6:80.
Container port 80 is available at localhost:3001.
##################### Environment started. #############################################################
Run /tmp/f49fceb1.sh in your existing console to also get connected.
```

Windows Testing screenshot:
image

Linux WSL testing screenshot:
image

### CODE REVIEW

**Review by Tatsinnit — COMMENTED** [review]
Thank you so much for pings!! Looks good to me, given its mostly code movement let's get nicely tested will be my 2 cents, thank you. ☕️☕️🎊❤️

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 1]
```diff
@@ -454,6 +398,20 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
                                                 cancellationToken: cancellationToken,
                                                 out string outPut);
 
+                    //  exit code not equal to zero occurs when pkexec doesn't have root access and have to retry with sudo
+                    if (launchExitCode != 0 && _platform.IsLinux && !_environmentVariables.IsCodespaces) {
+                         _log.Info($"pkexec failed with exitCode {launchExitCode}, retrying with sudo");
```
[the remark this answers is not in the document]
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs:403]: @Tatsinnit Yes, I will update the comments but whole idea to try with ```sudo``` if pkexec doesn't work and this would not happen 100% but for some users. Also I will update the logger variable.

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 2]
```diff
@@ -454,6 +398,20 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
                                                 cancellationToken: cancellationToken,
                                                 out string outPut);
 
+                    //  exit code not equal to zero occurs when pkexec doesn't have root access and have to retry with sudo
+                    if (launchExitCode != 0 && _platform.IsLinux && !_environmentVariables.IsCodespaces) {
+                         _log.Info($"pkexec failed with exitCode {launchExitCode}, retrying with sudo");
+                        (fileName, command) = await GetEndpointManagerLaunchArguments(currentUserName, logFileDirectory, cancellationToken);
+                        fileName = "sudo"; // replace pkexec with sudo
```
[the remark this answers is not in the document]
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs:405]: if user doesn't have sudo access, it would still fail but atleast this is another try for users for who had pkexec failed but had sudo access. For non-sudo user I will look into see how to handle this further. Thank you.

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 3]
```diff
@@ -494,6 +452,84 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
             }
         }
 
+        public Dictionary<string, string> GetEnvironmentVariables()
+        {
```
[the remark this answers is not in the document]
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs:456]: Yes, this will tested heavily E2E by testing team and then merged.

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 4]
```diff
@@ -494,6 +452,84 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
...
+            var fileName = string.Empty;
+            var command = string.Empty;
+            var executableName = $"{EndpointManager.ProcessName}{(_platform.IsWindows ? ".exe" : string.Empty)}";
+            var launcherPath = _fileSystem.Path.Combine(_fileSystem.Path.GetExecutingAssemblyDirectoryPath(), EndpointManager.DirectoryName, executableName);
+            if (!_fileSystem.FileExists(launcherPath))
+            {
+                throw new InvalidOperationException($"Failed to find '{launcherPath}'.");
+            }
+
+            switch (_platform)
```
[the remark this answers is not in the document]
Comment (peterbom) [reply src/library/EndpointManagement/EndpointManagementClient.cs:479]: `_platform` is a private field in the class, isn't it? In that case, I think that's very conventional C# naming, so I wouldn't be inclined to change anything.

[the remark this answers is not in the document]
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs:479]: Yep it is private field. I will resolve this comment.

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 5]
```diff
@@ -494,6 +454,84 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
...
+                        Process.Start(this.GetEndpointManagerLaunchInfoWindows($"\"{launcherPath}\"", quotedArguments));
+                    }
+
+                    await CheckEndpointManagerAliveAsync(cancellationToken);
+
+                    break;
+
+                case var platform when platform.IsOSX:
+
+                    var quotedLaunchPathAndArguments = $"\\\\\\\"{launcherPath}\\\\\\\" \\\\\\\"{currentUserName}\\\\\\\" \\\\\\\"{_socketFilePath}\\\\\\\" \\\\\\\"{logFileDirectory}\\\\\\\" \\\\\\\"{_operationContext.CorrelationId}\\\\\\\"";
```
Comment (peterbom) [inline src/library/EndpointManagement/EndpointManagementClient.cs:505]: I know it was already like this, but...given the number of backslashes it might be clearer to use a verbatim string literal, like:
```csharp
var quotedLaunchPathAndArguments = @$"\\\""{launcherPath}\\\"" \\\""{currentUserName}\\\"" \\\""{_socketFilePath}\\\"" \\\""{logFileDirectory}\\\"" \\\""{_operationContext.CorrelationId}\\\""";
```

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 6]
```diff
@@ -494,6 +454,84 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
...
+                _log.Info("Setting the '{0}' environment variable with '{1}' while launching '{2}'.", EnvironmentVariables.Names.DotNetRoot, _environmentVariables.DotNetRoot, EndpointManager.ProcessName);
+                return new Dictionary<string, string>() { { EnvironmentVariables.Names.DotNetRoot, _environmentVariables.DotNetRoot } };
+            }
+
+            return null;
+        }
+
+        public async Task<(string fileName, string command)> GetEndpointManagerLaunchArguments(string currentUserName, string logFileDirectory, CancellationToken cancellationToken)
+        {
+            var fileName = string.Empty;
```
Comment (peterbom) [inline src/library/EndpointManagement/EndpointManagementClient.cs:470]: I think it'd be preferable to declare `fileName` and `command` _and return them_ in each branch of the `_platform` switch. This avoids bugs arising from forgetting a `break` or forgetting to assign them in one of the branches. I notice they don't get set in the `platform.IsWindows` branch, and I wonder if they should be? If not, then explicitly returning `("", "")` from that branch would make that decision clearer.

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 7]
```diff
@@ -494,6 +454,84 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
...
+            if (!string.IsNullOrEmpty(_environmentVariables.DotNetRoot))
+            {
+                _log.Info("Setting the '{0}' environment variable with '{1}' while launching '{2}'.", EnvironmentVariables.Names.DotNetRoot, _environmentVariables.DotNetRoot, EndpointManager.ProcessName);
+                return new Dictionary<string, string>() { { EnvironmentVariables.Names.DotNetRoot, _environmentVariables.DotNetRoot } };
+            }
+
+            return null;
+        }
+
+        public async Task<(string fileName, string command)> GetEndpointManagerLaunchArguments(string currentUserName, string logFileDirectory, CancellationToken cancellationToken)
```
Comment (peterbom) [inline src/library/EndpointManagement/EndpointManagementClient.cs:468]: Should this be `private` instead of `public`?

File: src/library/EndpointManagement/EndpointManagementClient.cs [hunk 8]
```diff
@@ -454,6 +398,22 @@ private async Task EnsureEndpointManagerRunningAsync(CancellationToken cancellat
                                                 cancellationToken: cancellationToken,
                                                 out string outPut);
 
+                    // pkexec allows an authorized user to execute PROGRAM as another user. Refer - https://linux.die.net/man/1/pkexec
+                    // if pkexec failed then launchExitCode will not be zero, so giving user another chance to try with sudo. 
+                    // But this might fail for users who don't have sudo access. This is specifically for Linux.
+                    if (launchExitCode != 0 && _platform.IsLinux && !_environmentVariables.IsCodespaces) {
+                         _log.Info($"pkexec failed with exitCode {launchExitCode}, retrying with sudo");
+                        (fileName, command) = await GetEndpointManagerLaunchArguments(currentUserName, logFileDirectory, cancellationToken);
```
Comment (peterbom) [inline src/library/EndpointManagement/EndpointManagementClient.cs:406]: Is there a need to call `GetEndpointManagerLaunchArguments` again? Wouldn't the logic be identical if this line was removed?

File: src/library/EndpointManagement/EndpointManagementClient.cs (hunk 6 above)
Comment (peterbom) [reply src/library/EndpointManagement/EndpointManagementClient.cs:470]: Thinking about this some more, I'm wondering if it'd make more sense to have completely separate code paths for the different platforms. One of the key benefits of performing the conditional logic inside the function is that the caller shouldn't need to care which platform it is. But in this case, the caller does need to know that, because only under certain circumstances does it make sense to swap `pkexec` with `sudo`.

I'm thinking along the lines of separate classes for each platform, and the Linux one would internally do the retry with `sudo`.

This would also address another slight concern I had, which is that this function is doing a lot more stuff in the Windows branch, i.e. it's launching a process _and_ waiting for the endpoint manager to become ready.

Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs:470]: updated, thank for the suggestion @peterbom

File: src/library/EndpointManagement/EndpointManagementClient.cs (hunk 7 above)
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs]: done.

File: src/library/EndpointManagement/EndpointManagementClient.cs (hunk 8 above)
Comment (hsubramanianaks) [reply src/library/EndpointManagement/EndpointManagementClient.cs]: good point , updated them.

**Review by peterbom — APPROVED** [review]

**Review by Tatsinnit — APPROVED** [review]
❤️☕️🔔 Nice - awesome @peterbom, @hsubramanianaks   - I see your collab PR as well. I guess only need resolutions of open comments. Thanks heaps.
